import { useEffect, useRef, useState } from 'react';
import './CanvasEditor.css';
import { createShapeObject, selectRootIds, selectSelectedIds, useSceneStore } from '../features/scene';
import { sceneHistory } from '../features/scene/history/sceneHistory';
import { UpdateTransformCommand } from '../features/scene/history/commands';
import { useAssetStore } from '../features/assets';
import { getSnappedDrag } from '../features/scene/dragSnap';
import AlignmentGuides from './AlignmentGuides';
import './AlignmentGuides.css';

const colorFor=(v,f)=>/^#[0-9a-f]{6}$/i.test(v||'')?v:f;
const drawCharacter=(ctx,o,a)=>{const p=o.parts||{};const skin=colorFor(p.head,'#f2c9a5'),hair=colorFor(p.hair,'#3f2d20'),body=colorFor(p.body,'#4b5563'),eye=colorFor(p.eyes,'#202228'),mouth=colorFor(p.mouth,'#b34b5d');ctx.fillStyle=skin;ctx.beginPath();ctx.arc(0,-50,18,0,Math.PI*2);ctx.fill();ctx.fillStyle=hair;ctx.beginPath();ctx.arc(0,-58,18,Math.PI,0);ctx.fill();ctx.fillStyle=eye;ctx.beginPath();ctx.arc(-6,-52,2,0,Math.PI*2);ctx.arc(6,-52,2,0,Math.PI*2);ctx.fill();ctx.strokeStyle=mouth;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-4,-46);ctx.lineTo(4,-46);ctx.stroke();ctx.strokeStyle=body;ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(0,-32);ctx.lineTo(0,28);ctx.stroke();ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(-18,-20);ctx.lineTo(-13,8);ctx.lineTo(-18,32);ctx.moveTo(18,-20);ctx.lineTo(23,8);ctx.lineTo(18,32);ctx.stroke();ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(-8,28);ctx.lineTo(-12,58);ctx.moveTo(8,28);ctx.lineTo(12,58);ctx.stroke();};

export default function CanvasEditor(){
 const canvasRef=useRef(null),initializedRef=useRef(false);const [interaction,setInteraction]=useState(null);const [guides,setGuides]=useState({x:null,y:null});
 const objects=useSceneStore(s=>s.objects),rootIds=useSceneStore(selectRootIds),selectedIds=useSceneStore(selectSelectedIds),addObject=useSceneStore(s=>s.addObject),selectObject=useSceneStore(s=>s.selectObject),toggleObjectSelection=useSceneStore(s=>s.toggleObjectSelection),clearSelection=useSceneStore(s=>s.clearSelection),assets=useAssetStore(s=>s.assets);
 useEffect(()=>{if(initializedRef.current||rootIds.length)return;initializedRef.current=true;addObject(createShapeObject({name:'Demo Shape',transform:{x:50,y:50,rotation:0,scaleX:1,scaleY:1},width:50,height:50}))},[addObject,rootIds.length]);
 useEffect(()=>{const c=canvasRef.current;if(!c)return;const ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);rootIds.forEach(id=>{const o=objects[id];if(!o||!o.visible)return;const{x,y,rotation,scaleX,scaleY}=o.transform;ctx.save();ctx.translate(x,y);ctx.rotate(rotation*Math.PI/180);ctx.scale(scaleX,scaleY);if(o.type==='shape'){ctx.fillStyle=o.fill;if(o.shape==='circle'){ctx.beginPath();ctx.arc(o.width/2,o.height/2,Math.min(o.width,o.height)/2,0,Math.PI*2);ctx.fill()}else ctx.fillRect(0,0,o.width,o.height)}else if(o.type==='text'){ctx.fillStyle=o.fill;ctx.font=`${o.fontSize}px ${o.fontFamily}`;ctx.fillText(o.text,0,o.fontSize)}else if(o.type==='character')drawCharacter(ctx,o,assets[o.characterId]);ctx.restore()});},[objects,rootIds,assets]);
 const point=e=>{const r=canvasRef.current.getBoundingClientRect();return{x:(e.clientX-r.left)*canvasRef.current.width/r.width,y:(e.clientY-r.top)*canvasRef.current.height/r.height}};
 const hit=(p,o)=>{const{x,y,scaleX,scaleY}=o.transform,w=(o.width||40)*scaleX,h=(o.height||40)*scaleY;return p.x>=x&&p.x<=x+w&&p.y>=y-(o.type==='character'?70:0)&&p.y<=y+h};
 const down=e=>{const p=point(e);for(let i=rootIds.length-1;i>=0;i--){const o=objects[rootIds[i]];if(!o||!o.visible||o.locked||!hit(p,o))continue;const multi=e.shiftKey||e.ctrlKey||e.metaKey;if(multi)toggleObjectSelection(o.id);else if(!selectedIds.includes(o.id))selectObject(o.id);setInteraction({id:o.id,offsetX:p.x-o.transform.x,offsetY:p.y-o.transform.y,before:{...o.transform}});return}clearSelection()};
 const move=e=>{if(!interaction)return;const p=point(e),o=useSceneStore.getState().objects[interaction.id];if(!o||o.locked)return;const snapped=getSnappedDrag(useSceneStore.getState().objects,o.id,p.x-interaction.offsetX,p.y-interaction.offsetY);const state=useSceneStore.getState();const ids=state.selectedIds.includes(o.id)?state.selectedIds:[o.id];ids.forEach(id=>{const item=state.objects[id];if(item&&!item.locked)state.updateTransform(id,{x:item.transform.x+(snapped.x-o.transform.x),y:item.transform.y+(snapped.y-o.transform.y)})});setGuides({x:snapped.guideX,y:snapped.guideY})};
 const up=()=>{if(!interaction)return;const o=useSceneStore.getState().objects[interaction.id];if(o&&JSON.stringify(interaction.before)!==JSON.stringify(o.transform))sceneHistory.execute(new UpdateTransformCommand(o.id,{...o.transform},interaction.before));setGuides({x:null,y:null});setInteraction(null)};
 return <div className="canvas-container" style={{position:'relative'}}><canvas ref={canvasRef} width={800} height={500} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerLeave={up}/><AlignmentGuides guides={guides}/></div>;
}